### ISSUE TITLE
error when creating a new page: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-confluence#4]
```ruby
$ asciidoctor-confluence --host HOST --spaceKey MT --title TITLE --username USERNAME--password PWD file.adoc
An error occurred, the page has not been created because:
undefined method `+' for nil:NilClass
```
Is there a way to enable stack traces ?

Here is my version (latest from master branch):
```ruby
$ asciidoctor-confluence -V

Asciidoctor-confluence v0.0.2
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:- ex:CP850)
c:/dev/softs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-confluence-0.0.2/bin/asciidoctor-confluence:7:in `exit': no implicit conversion from nil to integer (TypeError)
        from c:/dev/softs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-confluence-0.0.2/bin/asciidoctor-confluence:7:in `<top (required)>'
        from c:/dev/softs/Ruby22-x64/bin/asciidoctor-confluence:23:in `load'
        from c:/dev/softs/Ruby22-x64/bin/asciidoctor-confluence:23:in `<main>'
```

Thanks :smile:

**Comment by gscheibel** [comment]
@Mogztter just to be sure, you replace all the HOST, TITLE etc mentions by real values ? 
a space between the username and the '--password' attribute is messing (probably because of the the username replacement).

Have you checked if the page is really missing in Confluence ?

**Comment by gscheibel** [comment]
BTW, can you reproduce the issue with the docker container ? (at the moment I can't reproduce the issue)

**Comment by Mogztter** [comment]
I'm on a corporate Windows (meaning no Docker :smile:) but I will test it on my desktop.

>  just to be sure, you replace all the HOST, TITLE etc mentions by real values ? 
a space between the username and the '--password' attribute is messing (probably because of the the username replacement).

Yes I did replace with my username, password, host...

> at the moment I can't reproduce the issue

Me neither :disappointed_relieved: ?! I don't know what happened...
My error is now related to my Confluence setup: `Can't connect to the remote host... connect(2) for nil port 80`

Sorry about that :open_mouth:

**Comment by Mogztter** [comment]
@gscheibel Too bad we are using confluence 5.3 :cry:

**Comment by gscheibel** [comment]
I've tested against Confluence 5.6.5, I'll try with 5.3

**Comment by msettro** [comment]
Using Confluence 5.1.3 the same error occurs
```
An error occurred, the page has not been created because:
undefined method `+' for nil:NilClass
```
