### ISSUE TITLE
Generate XHTML output

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-confluence#7]
As a user
I want to generate XHTML output
So Confluence will accept it as valid markup.

This involves setting the Asciidoctor options in Asciidoctor::Confluence::Publisher as follows:

```
@asciidoctor_options[:backend] = 'xhtml'
```

**Comment by carlosjgpCrunch** [comment]
An error occurred, the page has not been updated because:
Error parsing xhtml: Unexpected close tag </colgroup>; expected </col>.
 at [row,col {unknown-source}]: [73,10]

**Comment by eliezio** [comment]
I solved a similar problem by appending "-- -b xhtml5" to the command line. This forced asciidoctor to generate XHTML compliant output.

**Comment by r-vanooyen** [comment]
pullrequest #26 would fix that too. Is there a possibility to merge that PR and create a new version 0.0.3?

**Comment by mojavelinux** [comment]
I went ahead and merged it. However, I don't have rights to publish the gem. The best thing to do would be to set up automated publishing of the gem via GitHub Actions so it can be released easily on demand.

**Comment by mojavelinux** [comment]
FYI, I'd say this project is looking for a new maintainer who can keep it current and published. Let's chat in the project chat at https://asciidoctor.zulipchat.com.
